name: CI

# credit: https://github.com/hungrybluedev/geo/blob/main/.github/workflows/ci.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            make: make
          - name: macos-latest
            make: make
          - name: windows-latest
            make: .\make.bat
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Build V and symlink
        run: |
          cd ..
          git clone https://github.com/vlang/v.git --depth 1 v
          cd v
          ${{ matrix.os.make }}
          ./v symlink -githubci
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Build ${{ github.event.repository.name }}
        run:  make prod
      - name: Build doc
        run:  make doc
      - name: Run Tests
        run: make test
